kind: Secret
apiVersion: v1
metadata:
  name: examplecompany-helm-repo-credentials
  annotations:
    avp.kubernetes.io/path: "examplecompany/data/infrastructure/github/tokens/example_token"
type: Opaque
stringData:
  EXAMPLE_COMPANY_HELM_USERNAME: <username>
  EXAMPLE_COMPANY_HELM_PASSWORD: <token>
  EXAMPLE_COMPANY_HELM_REPO_URL: https://example.com/repo/url

