kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
type: Opaque
stringData:
  AVP_TYPE: vault
  AVP_AUTH_TYPE: k8s
  AVP_K8S_MOUNT_PATH: auth/mount_path
  AVP_K8S_ROLE: argocd
  VAULT_ADDR: https://vault.addr

