apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  replicas: 5
  template:
    metadata:
      annotations:
        ad.datadoghq.com/argocd-application-controller.checks: |
          {
            "argocd": {
              "init_config": {},
              "instances": [
                {
                  "app_controller_endpoint": "http://%%host%%:8082/metrics"
                }
              ]
            }
          }  
    spec:
      containers:
      - name: argocd-application-controller
        env:
        - name: ARGOCD_CONTROLLER_REPLICAS
          value: "5"
        command:
        - argocd-application-controller
        - '--redis'
        - 'argocd-redis-ha-haproxy:6379'
