apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:demo, applications, create, demo/*, allow

    g, example-github-org:example-team, role:demo