apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-application-controller
  annotations:
    iam.gke.io/gcp-service-account: "argocd-application-controller@example-gcp-project.iam.gserviceaccount.com"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-server
  annotations:
    iam.gke.io/gcp-service-account: "argocd-server@example-gcp-project.iam.gserviceaccount.com"
