apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
type: Opaque
stringData:
  slack-token: <path:examplecompany/data/infrastructure/argocd/slack/argocd-notifications-bot-oauth-access-token#token>
