apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-webpage-deployment
spec:
  selector:
    matchLabels:
      app: test-webpage
      stack: green
  replicas: 1
  template:
    metadata:
      labels:
        app: test-webpage
        stack: green
    spec:
      containers:
        - name: test-webpage
          image: test-webpage:green
          imagePullPolicy: Never
          ports:
          - containerPort: 80
