apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-webpage
spec:
  selector:
    matchLabels:
      app: test-webpage
  replicas: 1
  template:
    metadata:
      labels:
        app: test-webpage
    containers:
      imagePullSecrets:
        - name: regcred
      imagePullPolicy: Always
