apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -blue
namespace: test-webpage
commonLabels:
  stack: blue

resources:
- ../../base/app/

patches:
- patches/deployment.yaml

images:
  - name: test-webpage
    newName: docker.io/shardy107/bluegreen
    newTag: blue
