apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.17/manifests/ha/install.yaml
  - resources/ingress.yaml
  - resources/vault-auth-secret.yaml
  - resources/examplecompany-helm-repo-secret.yaml
  - resources/projects.yaml
  - resources/repos.yaml

patchesStrategicMerge:
  - patches/rbac-cm.yaml
  - patches/cm.yaml
  - patches/repo-server.yaml
  - patches/server.yaml
  - patches/secret.yaml
  - patches/service-account.yaml
  - patches/application-server.yaml
  - patches/argocd-cmd-params-cm.yaml
  - patches/notification-configmap.yaml
  - patches/slack-token-secret.yaml
