apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-green

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.17/manifests/ha/install.yaml

components:
  - ../../components/argocd-components/

