apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: 'argo-cd:/ConfigMap:argocd/argocd-cm'
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  application.resourceTrackingMethod: annotation
  accounts.image-updater: apiKey
  accounts.image-updater.enabled: "true"
  server.rbac.log.enforce.enable: "true"
  resource.customizations: |
    networking.k8s.io/Ingress:
        health.lua: |
          hs = {}
          hs.status = "Healthy"
          return hs
  configManagementPlugins: |
    - name: argocd-vault-plugin-kustomize
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build . | argocd-vault-plugin generate -"]
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: demo_client_id
          clientSecret: $demo_client_secret
          orgs:
          - name: demo_org
  url: 'https://argo.address/
