apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  replicas: 5
  template:
    metadata:
        annotations:
          ad.datadoghq.com/argocd-repo-server.checks: |
            {
              "argocd": {
                "init_config": {},
                "instances": [
                  {
                    "repo_server_endpoint": "http://%%host%%:8084/metrics"
                  }
                ]
              }
            }
    spec:
      automountServiceAccountToken: true
      volumes:
        - emptyDir: {}
          name: custom-tools
      containers:
      - name: argocd-repo-server
        volumeMounts:
          - mountPath: /usr/local/bin/vault
            name: custom-tools
            subPath: vault
          - mountPath: /usr/local/bin/argocd-vault-plugin
            name: custom-tools
            subPath: argocd-vault-plugin
          - mountPath: /usr/local/bin/jq
            name: custom-tools
            subPath: jq
          - mountPath: /usr/local/bin/yq
            name: custom-tools
            subPath: yq
          - mountPath: /usr/local/bin/ejson
            name: custom-tools
            subPath: ejson
        envFrom:
          - secretRef:
              name: argocd-vault-plugin-credentials
          - secretRef:
              name: examplecompany-helm-repo-credentials
      initContainers:
        - name: download-tools
          command:
            - sh
            - '-c'
          args:
              - apk --no-cache add --update curl && curl -L "https://releases.hashicorp.com/vault/1.1.2/vault_1.1.2_linux_amd64.zip"
                --output ./vault_1.1.2_linux_amd64.zip && unzip ./vault_1.1.2_linux_amd64.zip
                && chmod +x ./vault && mv ./vault /custom-tools/ && curl -L  https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v1.11.0/argocd-vault-plugin_1.11.0_linux_amd64
                --output ./argocd-vault-plugin && chmod +x ./argocd-vault-plugin && mv ./argocd-vault-plugin
                /custom-tools/ && curl -L "https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64"
                --output ./jq && chmod +x ./jq && mv ./jq /custom-tools/ && curl -L "https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64"
                --output ./yq && chmod +x ./yq && mv ./yq /custom-tools/ && curl -L "https://github.com/Shopify/ejson/releases/download/v1.3.3/ejson_1.3.3_linux_amd64.tar.gz"
                --output ./ejson_1.3.3_linux_amd64.tar.gz && tar -xzvf ejson_1.3.3_linux_amd64.tar.gz
                && chmod +x ./ejson && mv ./ejson /custom-tools/
          image: 'alpine:3.8'
          env:
            - name: AVP_VERSION
              value: 1.11.0
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
