apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-application-controller
  annotations:
    iam.gke.io/gcp-service-account: "argocd-application-controller@non-prod-internal-svcs.iam.gserviceaccount.com"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-server
  annotations:
    iam.gke.io/gcp-service-account: "argocd-server@non-prod-internal-svcs.iam.gserviceaccount.com"
