apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-webpage
spec:
  generators:
  - list:
      elements:
      - cluster: example-cluster
        stack: green
      - cluster: example-cluster
        stack: blue
  template:
    metadata:
      name: 'test-webpage-{{ stack }}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: test-webpage
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - Validate=false
          - Prune=false
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      source: 
        repoURL: 'git@github.com:Zemur/bluegreen-manifests.git'
        path: apps/test-webpage/overlays/{{ stack }}
        targetRevision: main
      destination:
        name:  '{{ cluster }}'
        namespace: test-webpage
