apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/blue
  - ../../../../base/argocd-bluegreen-ingress

patches:
  - target:
      version: v1
      kind: ServiceAccount
      name: argocd-server
    patch: |-
      - op: add
        path: /metadata/annotations/iam.gke.io~1gcp-service-account
        value: argocd-server@non-prod-internal-svcs.iam.gserviceaccount.com
  - target:
      version: v1
      kind: ServiceAccount
      name: argocd-application-controller
    patch: |-
      - op: add
        path: /metadata/annotations/iam.gke.io~1gcp-service-account
        value: argocd-application-controller@non-prod-internal-svcs.iam.gserviceaccount.com
